copen/urls.py
#urls - view - template

from django.urls import path, include
from .views import Copen, ApreensaoAddView, OcorrenciaView, buscar_interno, filtrar_objetos_htmx, AtendimentoView, \
    CustodiaAddView, CustodiaEditView, MpAddView, ApreensaoRelatorioView, relatorio_resumido_apreensao

app_name = 'copen'

urlpatterns = [
    path('', Copen.as_view(), name='copen'),
    path('atendimento-add/', AtendimentoView.as_view(), name='atendimento-add'),
    path('apreensao-add/', ApreensaoAddView.as_view(), name='apreensao-add'),
    path('ocorrencia-add/', OcorrenciaView.as_view(), name='ocorrencia-add'),
    path('custodia-add/', CustodiaAddView.as_view(), name='custodia-add'),
    path('mp-add/', MpAddView.as_view(), name='mp-add'),
    path('custodia-edit/<int:pk>', CustodiaEditView.as_view(), name='custodia-edit'),
    #relatorios
    path('apreensao-relatorio/', ApreensaoRelatorioView.as_view(), name='apreensao-relatorio'),


    #pdf_relatorios
    path('relatorio-resumido-apreensao/', relatorio_resumido_apreensao, name='relatorio-resumido-apreensao'),

    #partials htmx
    path('buscar-interno/', buscar_interno, name='buscar-interno'),
    path('filtrar-objetos/', filtrar_objetos_htmx, name='filtrar-objetos'),


]

gesipe/urls.py
#urls - view - template

from django.urls import path, include
from .views import (Gesipe, GesipeAdm, GesipeAdmEdit,
                    GesipeAdmLote, GesipeArmaria,
                    GesipeSga, RelatorioGesipeAdm,
                    RelatorioGesipeSga, GesipeSgaAdd, GesipeSgaEdit,
                    GesipeSgaLote
                    )


app_name = 'gesipe'

urlpatterns = [
    path('', Gesipe.as_view(), name='gesipe'),
    path('gesipe_adm', GesipeAdm.as_view(), name='gesipe_adm'),
    path('gesipe_adm/edit/<int:pk>', GesipeAdmEdit.as_view(), name='gesipe_adm_edit'),
    path('gesipe_adm_lote/', GesipeAdmLote.as_view(), name='gesipe_adm_lote'),
    path('gesipe_armaria/', GesipeArmaria.as_view(), name='gesipe_armaria'),
    path('gesipe_sga/', GesipeSga.as_view(), name='gesipe_sga'),
    path('relatorio_gesipe_adm', RelatorioGesipeAdm.as_view(), name='relatorio_gesipe_adm'),
    path('relatorio_gesipe_adm/export_pdf/', RelatorioGesipeAdm.as_view(), name='relatorio_gesipe_adm_export_pdf'),
    path('gesipe_sga_add/', GesipeSgaAdd.as_view(), name='gesipe_sga_add'),
    path('gesipe_sga/edit/<int:pk>', GesipeSgaEdit.as_view(), name='gesipe_sga_edit'),
    path('relatorio_gesipe_sga', RelatorioGesipeSga.as_view(), name='relatorio_gesipe_sga'),
    path('gesipe_sga_lote/', GesipeSgaLote.as_view(), name='gesipe_sga_lote'),


]

servidor/urls.py
#urls - view - template

from django.urls import path, include
from .views import RecursosHumanosPage, CriarServidorView, \
    ServidorEdit, export_to_pdf, ServidorLote, \
    RelatorioRh, ServidorDetail, pdf_wait, check_task_status, \
    documento_delete



app_name = 'servidor'

urlpatterns = [
    path('', RecursosHumanosPage.as_view(), name='recursos_humanos'),
    path('criar/', CriarServidorView.as_view(), name='criar_servidor'),
    path('edit/<int:pk>', ServidorEdit.as_view(), name='servidor_edit'),
    path('export-to-pdf/', export_to_pdf, name='export_to_pdf'),
    path('lote/', ServidorLote.as_view(), name='servidor_lote'),
    path('relatorio_rh', RelatorioRh.as_view(), name='relatorio_rh'),
    path('detail/<int:pk>', ServidorDetail.as_view(), name='servidor_detail'),
    path('pdf-wait/', pdf_wait, name='pdf_wait'),
    path('check-task/', check_task_status, name='check_task_status'),
path('documento/<int:documento_id>/delete/', documento_delete, name='documento_delete'),





]

siteservidores/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


# Apontando para a view custom_403 do app seappb
handler403 = 'seappb.views.custom_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('seappb.urls', namespace='seappb')),
    path('gesipe/', include('gesipe.urls', namespace='gesipe')),
    path('ajuda_custo/', include('ajuda_custo.urls', namespace='ajuda_custo')),
    path('servidor/', include('servidor.urls', namespace='servidor')),
    path('copen/', include('copen.urls', namespace='copen')),
    path('interno/', include('interno.urls', namespace='interno')),
    path('gestao_prisional/', include('gestao_prisional.urls', namespace='gestao_prisional')),
    path('armaria/', include('armaria.urls', namespace='armaria')),
    path('chained/', include('smart_selects.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gesipe/views.py
from django.shortcuts import render, redirect
from .models import Gesipe_adm, Gesipe_Sga
from django.views.generic.edit import FormView, UpdateView, CreateView, View
from django.utils.timezone import now
from .forms import GesipeAdmForm, UploadFileForm, GesipeSgaForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q, Sum, F  # Para pesquisas com OR lógico
from django.utils import timezone
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.http import JsonResponse
from datetime import datetime, date
import openpyxl
from servidor.models import Servidor
from io import BytesIO
import zipfile
from django.http import HttpResponse
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, Image, Frame
from reportlab.lib.styles import getSampleStyleSheet
from django.contrib.staticfiles import finders
from django.contrib.auth.mixins import UserPassesTestMixin
from django.template.loader import get_template
from weasyprint import HTML



# Create your views here.

# url - view - html


#exportar relatorios para pdf

def export_pdf(request):
    # Pega as datas de filtro do request recebido
    data_inicial = request.GET.get('dataInicial')
    data_final = request.GET.get('dataFinal')

    # Filtra o queryset com as datas fornecidas
    queryset = RelatorioGesipeAdm().get_queryset()  # Chama o queryset da view manualmente, se necessário
    if data_inicial and data_final:
        try:
            data_inicial = datetime.strptime(data_inicial, '%Y-%m-%d').date()
            data_final = datetime.strptime(data_final, '%Y-%m-%d').date()
            queryset = queryset.filter(data__range=(data_inicial, data_final))
        except ValueError:
            pass  # Ignora erros de formato de data

    # Renderiza o template HTML com os dados filtrados
    template = get_template('relatorio_gesipe_pdf.html')
    context = {
        'object_list': queryset,  # Dados filtrados para o PDF
        'dataInicial': data_inicial,
        'dataFinal': data_final,
        'setor': 'Administrativo',
    }
    html = template.render(context)

    # Gera e retorna o PDF
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = "attachment; filename='relatorio_gesipe_adm.pdf'"
    HTML(string=html).write_pdf(response)
    return response


def export_pdf_sga_detalhado(request, setor):
    # Pega as datas de filtro do request recebido
    data_inicial = request.GET.get('dataInicial')
    data_final = request.GET.get('dataFinal')

    # Filtra o queryset com as datas fornecidas
    queryset = RelatorioGesipeSga().get_queryset()  # Chama o queryset da view manualmente, se necessário
    if data_inicial and data_final:
        try:
            data_inicial = datetime.strptime(data_inicial, '%Y-%m-%d').date()
            data_final = datetime.strptime(data_final, '%Y-%m-%d').date()
            queryset = queryset.filter(data__range=(data_inicial, data_final))
        except ValueError:
            pass  # Ignora erros de formato de data

    # Renderiza o template HTML com os dados filtrados
    template = get_template('sga/relatorio_gesipe_sga_pdf_detalhado.html')
    context = {
        'object_list': queryset,  # Dados filtrados para o PDF
        'dataInicial': data_inicial,
        'dataFinal': data_final,
        'setor': setor,
    }
    html = template.render(context)

    # Gera e retorna o PDF
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = "attachment; filename='relatorio_gesipe_sga_detalhado.pdf'"
    HTML(string=html).write_pdf(response)
    return response



class GesipeArmaria(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Servidor
    template_name = "gesipe_armaria.html"
    context_object_name = 'servidores'
    paginate_by = 20
    max_pdfs = 50  # Limite máximo de PDFs

    def test_func(self):
        user = self.request.user
        grupos_permitidos = ['Administrador', 'Armaria']
        return user.groups.filter(name__in=grupos_permitidos).exists()

    def handle_no_permission(self):
        messages.error(self.request, "Você não tem permissão para acessar esta página.")
        return render(self.request, '403.html', status=403)

    def get_queryset(self):
        queryset = Servidor.objects.all()
        query = self.request.GET.get('query')
        if query:
            queryset = queryset.filter(
                Q(nome__icontains=query) | Q(matricula__icontains=query)
            )

        cargo = self.request.GET.get('cargo')
        if cargo:
            queryset = queryset.filter(cargo=cargo)

        local_trabalho = self.request.GET.get('local_trabalho')
        if local_trabalho:
            queryset = queryset.filter(local_trabalho__icontains=local_trabalho)

        cargo_comissionado = self.request.GET.get('cargo_comissionado')
        if cargo_comissionado == "None":
            cargo_comissionado = ""

        if cargo_comissionado:
            queryset = queryset.filter(cargo_comissionado__icontains=cargo_comissionado)

        # Novo filtro de intervalo alfabético
        intervalo_alfabetico = self.request.GET.get('intervalo_alfabetico')
        if intervalo_alfabetico:
            if intervalo_alfabetico == 'A-E':
                queryset = queryset.filter(nome__regex=r'^[A-Ea-e]')
            elif intervalo_alfabetico == 'F-J':
                queryset = queryset.filter(nome__regex=r'^[F-Jf-j]')
            elif intervalo_alfabetico == 'K-O':
                queryset = queryset.filter(nome__regex=r'^[K-Ok-o]')
            elif intervalo_alfabetico == 'P-T':
                queryset = queryset.filter(nome__regex=r'^[P-Tp-t]')
            elif intervalo_alfabetico == 'U-Z':
                queryset = queryset.filter(nome__regex=r'^[U-Zu-z]')

        status = self.request.GET.get('status')
        if status:
            queryset = queryset.filter(status=status)

        genero = self.request.GET.get('genero')
        if genero:
            queryset = queryset.filter(genero__icontains=genero)

        return queryset.order_by('nome')


    def generate_pdf(self, servidor):
        # Definindo a largura e altura da página
        page_width, page_height = A4

        # Crie o buffer e o canvas
        pdf_buffer = BytesIO()
        c = canvas.Canvas(pdf_buffer, pagesize=(page_width, page_height))

        # Definindo margens
        margin_x = 2 * cm
        margin_y = page_height - 4 * cm  # Margem superior

        # Cabeçalho com as imagens
        logo_pb_path = finders.find('images/mini/GovPBT_mini.png')
        logo_seap_path = finders.find('images/mini/seap-pb_mini.png')
        logo_pp_path = finders.find('images/mini/pp_mini.png')

        def resize_image(img_path, max_width, max_height):
            img = Image(img_path)
            img.drawWidth = min(img.imageWidth, max_width)
            img.drawHeight = min(img.imageHeight, max_height)
            return img

        # Ajustar o tamanho das imagens
        logo_pb = resize_image(logo_pb_path, 2 * cm, 1 * cm)
        logo_seap = resize_image(logo_seap_path, 1 * cm, 1 * cm)
        logo_pp = resize_image(logo_pp_path, 2 * cm, 1 * cm)

        # Posicionamento das imagens com espaçamento
        start_x = margin_x
        start_y = margin_y - logo_pb.drawHeight
        spacing = 6 * cm

        logo_pb.drawOn(c, start_x, start_y)
        logo_seap.drawOn(c, start_x + logo_pb.drawWidth + spacing, start_y)
        logo_pp.drawOn(c, start_x + logo_pb.drawWidth + logo_seap.drawWidth + 2 * spacing, start_y)

        # Adicionando título centralizado
        c.setFont("Helvetica-Bold", 14)
        c.drawCentredString(page_width / 2, start_y - 4 * cm, "TERMO DE ACAUTELAMENTO DE COLETE BALÍSTICO")

        # Conteúdo principal do texto com quebra automática de linha
        styles = getSampleStyleSheet()
        text_style = styles["BodyText"]
        text_style.leading = 22  # Ajuste o espaçamento entre linhas aqui
        text = (
            f"Eu, {servidor.nome}, Policial Penal do Estado da Paraíba, matrícula {servidor.matricula}, "
            f"lotado(a) atualmente no(a) {servidor.local_trabalho}, RECEBI da Gerência Executiva do Sistema "
            "Penitenciário, um (01) colete balístico da Marca PROTECTA, o qual ficará sob minha guarda e responsabilidade, "
            "ressarcindo o erário por sua perda ou extravio, independente dos procedimentos que venham a ocorrer no "
            "âmbito administrativo e criminal."
        )

        # Usando Frame e Paragraph para a quebra de linha automática
        frame = Frame(margin_x, start_y - 12 * cm, page_width - 2 * margin_x, 6 * cm, showBoundary=False)
        story = [Paragraph(text, text_style)]
        frame.addFromList(story, c)

        # Informações adicionais
        y_position = start_y - 14 * cm
        c.setFont("Helvetica", 10)
        c.drawString(margin_x, y_position, "Tamanho     [     ] P               [     ] M               [     ] G")
        c.drawString(margin_x, y_position - 1 * cm, "Número de Série ____________________")
        c.drawString(margin_x, y_position - 2 * cm, "Data: ________/________/________")

        # Campos de assinatura com verificação do limite inferior
        signature_y_position = y_position - 5 * cm
        for line, label in enumerate([
            "Assinatura Policial Penal: ______________________________________",
            "CPF: ______________________________________",
            "Assinatura Chefe Imediato: ______________________________________",
            "Matrícula: ______________________________________",
            "Assinatura Membro da Comissão: ______________________________________",
            "Matrícula: ______________________________________"

gesipe/templates/gesipe_adm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block titulo %}
Gesipe Administrativo
{% endblock %}



{% block content %}
    <div class="container pt-32">


        <div class="container">
            <h1 class="text-center text-bold text-3xl pb-5 font-mono">Preencha as Informações:</h1>
        </div>

        <form class="form-group container border border-2 border-secondary" action="{% url 'gesipe:gesipe_adm' %}" method="POST">
            {% csrf_token %}


            <div class="grid lg:grid-cols-4 grid-cols-2 justify-items-stretch gap-4 px-3 py-4">
                {% for field in form %}
                  <div class="px-8">
                    <label class="form-label font-semibold lg:text-base text-2xl ">{{ field.label }}</label>
                    {{ field }}
                  </div>
                {% endfor %}
            </div>
             <div class="col-md-12 col-12 p-4 d-flex justify-content-center">
                <button type="submit" name="botao_submit" class="btn btn-success">Salvar informaçoes</button>
            </div>
            <hr>
            <!-- Adicione mais seções conforme necessário -->
        </form>
    </div>





{% endblock %}

gesipe/templates/gesipe_adm_data.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
Gesipe Data
{% endblock %}



{% block content %}
    <div class="flex flex-col justify-center pt-3">


        <div class="container">
            <h1 class="text-center p-3">Preencha as Informações</h1>
        </div>

        <form class="border border-2 border-secondary" action="" method="POST">
            {% csrf_token %}


            <div class="justify-center p-3">
                <label for="data_pesquisa" class="form-label">Digita a Data para inclusao ou edicao </label>
                <input type="date" class="form-control" id="data_pesquisa" aria-describedby="emailHelp">

            </div>
        </form>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">Data Já Existente</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Informacoes para data ja existentes, deseja editar?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                    <button type="button" class="btn btn-danger">Editar</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var myModal = new bootstrap.Modal(document.getElementById('myModal'));
            document.getElementById('botao_buscar').addEventListener('click', function() {
                myModal.show();
            });
        });
    </script>
{% endblock %}

gesipe/templates/gesipe_adm_lote.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block titulo %}
Gesipe Administrativo Editar
{% endblock %}



{% block content %}


<div class="flex flex-col justify-center pt-32">
    <div class="flex rounded-lg shadow-lg p-6 justify-center mx-20">
        <form class="flex flex-col justify-center" method="post" enctype="multipart/form-data">
            <div class="flex justify-center">
                {% csrf_token %}
                {{ form|crispy }}
            </div>
            <div class="flex justify-center">
                <button class="btn btn-primary" type="submit">Upload</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

gesipe/templates/gesipe_armaria.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}
Servidores
{% endblock %}


{% block content %}




<!--tabela com os servidores-->

<div class="w-full mb-12 flex px-4 md:px-12 justify-start">
    <div class="bg-white shadow-lg rounded-lg w-full">
        <div class="p-6 rounded-t-lg">
            <h1 class="text-3xl font-bold text-center py-8">Servidores e Equipamentos</h1>
                <form method="GET">

                    <div class="mt-4 px-0 grid grid-cols-4 w-full">
                        <div class="flex space-x-4 items-center">
                            <a href="{% static 'files/termo_acautelamento_coletes.docx' %}" class="btn btn-success" download>
                                Termo De Acautelamento Em branco
                            </a>
                            <a class="btn btn-primary" href="{% url 'gesipe:gesipe_armaria' %}?download_zip=true&query={{ request.GET.query }}&cargo={{ request.GET.cargo }}&local_trabalho={{ request.GET.local_trabalho }}&cargo_comissionado={{ request.GET.cargo_comissionado }}&intervalo_alfabetico={{ request.GET.intervalo_alfabetico }}&status={{ request.GET.status }}&genero={{ request.GET.genero }}">
                                Termo de Acautelamento Coletes
                            </a>

                        </div>
                        <div class="col-span-3 grid grid-cols-5 gap-2 px-2">
                            <input type="text" class="form-control col-span-2" name="local_trabalho" placeholder="Local de Trabalho..." value="{{ request.GET.local_trabalho }}">
                            <select class="form-control" name="cargo">
                                <option value="">Cargo...</option>
                                {% for cargo in cargos %}
                                <option value="{{ cargo }}" {% if request.GET.cargo == cargo %}selected{% endif %}>{{ cargo }}</option>
                                {% endfor %}
                            </select>
                            <select class="form-control" name="cargo_comissionado">
                                <option value="" selected>Cargo Comissionado...</option>
                                {% for cargo_comissionado in cargos_comissionado %}
                                    <option value="{{ cargo_comissionado }}">
                                        {{ cargo_comissionado }}
                                    </option>
                                {% endfor %}
                            </select>
                            <!-- Novo filtro de intervalo alfabético -->
                            <select class="form-control" name="intervalo_alfabetico">
                                <option value="">Intervalo Alfabético...</option>
                                <option value="A-E" {% if request.GET.intervalo_alfabetico == 'A-E' %}selected{% endif %}>A - E</option>
                                <option value="F-J" {% if request.GET.intervalo_alfabetico == 'F-J' %}selected{% endif %}>F - J</option>
                                <option value="K-O" {% if request.GET.intervalo_alfabetico == 'K-O' %}selected{% endif %}>K - O</option>
                                <option value="P-T" {% if request.GET.intervalo_alfabetico == 'P-T' %}selected{% endif %}>P - T</option>
                                <option value="U-Z" {% if request.GET.intervalo_alfabetico == 'U-Z' %}selected{% endif %}>U - Z</option>
                            </select>


                            <select class="form-control" name="genero">
                                <<option value="">Gênero...</option>
                                {% for genero in generos %}
                                <option value="{{ genero }}" {% if request.GET.genero == genero %}selected{% endif %}>{{ genero }}</option>
                                {% endfor %}>
                            </select>
                            <select class="form-control" name="status">
                                <option value="">Status...</option>
                                <option value="True" {% if request.GET.status == 'True' %}selected{% endif %}>Ativo</option>
                                <option value="False" {% if request.GET.status == 'False' %}selected{% endif %}>Inativo</option>
                            </select>
                            <div class="col-span-2">
                                <input type="text" name="query" id="searchInput" class="form-control" placeholder="Pesquisar..." value="{{ request.GET.query }}">
                            </div>
                            <button type="submit" class="btn btn-primary">Buscar</button>
                        </div>
                    </div>
                </form>

        </div>
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white divide-y divide-gray-200">
                <thead class="bg-gray-100">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nome</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Matrícula</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Cargo</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Local de Trabalho</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Cargo comissionado</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    {% for servidor in servidores %}
                    <tr class="clickable-row" data-href="{% url 'servidor:servidor_detail' servidor.id %}">
                        <td class="px-4 py-3 whitespace-nowrap">{{ servidor.nome }}</td>
                        <td class="px-4 py-3 whitespace-nowrap">{{ servidor.matricula }}</td>
                        <td class="px-4 py-3 whitespace-nowrap">{{ servidor.cargo }}</td>
                        <td class="px-4 py-3 whitespace-nowrap">{{ servidor.local_trabalho }}</td>
                        <td class="px-4 py-3 whitespace-nowrap">{% if servidor.cargo_comissionado %}{{ servidor.cargo_comissionado }}{% else %}{% endif %}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4" class="px-6 py-4 text-center text-gray-500">Nenhum servidor encontrado</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


        <!-- Paginação -->
        <div class="p-6 bg-gray-100 rounded-b-lg">
            <nav aria-label="Page navigation">
                <ul class="inline-flex items-center -space-x-px">
                    {% if page_obj.has_previous %}
                    <li>
                        <a href="?page=1&query={{ request.GET.query }}&cargo={{ request.GET.cargo }}&local_trabalho={{ request.GET.local_trabalho }}&cargo_comissionado={{ request.GET.cargo_comissionado }}&intervalo_alfabetico={{ request.GET.intervalo_alfabetico }}&status={{ request.GET.status }}&genero={{ request.GET.genero }}" class="px-3 py-2 ml-0 text-sm font-medium text-gray-500 bg-white rounded-l-lg border border-gray-300 hover:bg-gray-100">Primeira</a>
                    </li>
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}&query={{ request.GET.query }}&cargo={{ request.GET.cargo }}&local_trabalho={{ request.GET.local_trabalho }}&cargo_comissionado={{ request.GET.cargo_comissionado }}&intervalo_alfabetico={{ request.GET.intervalo_alfabetico }}&status={{ request.GET.status }}&genero={{ request.GET.genero }}" class="px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 hover:bg-gray-100">Anterior</a>
                    </li>
                    {% endif %}

                    {% for p in page_range %}
                    {% if p == page_obj.number %}
                    <li>
                        <span class="px-3 py-2 text-sm font-medium text-white bg-blue-500 border border-gray-300">{{ p }}</span>
                    </li>
                    {% else %}
                    <li>
                        <a href="?page={{ p }}&query={{ request.GET.query }}&cargo={{ request.GET.cargo }}&local_trabalho={{ request.GET.local_trabalho }}&cargo_comissionado={{ request.GET.cargo_comissionado }}&intervalo_alfabetico={{ request.GET.intervalo_alfabetico }}&status={{ request.GET.status }}&genero={{ request.GET.genero }}" class="px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 hover:bg-gray-100">{{ p }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}&query={{ request.GET.query }}&cargo={{ request.GET.cargo }}&local_trabalho={{ request.GET.local_trabalho }}&cargo_comissionado={{ request.GET.cargo_comissionado }}&intervalo_alfabetico={{ request.GET.intervalo_alfabetico }}&status={{ request.GET.status }}&genero={{ request.GET.genero }}" class="px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 hover:bg-gray-100">Próxima</a>
                    </li>
                    <li>
                        <a href="?page={{ page_obj.paginator.num_pages }}&query={{ request.GET.query }}&cargo={{ request.GET.cargo }}&local_trabalho={{ request.GET.local_trabalho }}&cargo_comissionado={{ request.GET.cargo_comissionado }}&intervalo_alfabetico={{ request.GET.intervalo_alfabetico }}&status={{ request.GET.status }}&genero={{ request.GET.genero }}" class="px-3 py-2 text-sm font-medium text-gray-500 bg-white rounded-r-lg border border-gray-300 hover:bg-gray-100">Última</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>

    </div>
</div>

<script>
    document.querySelectorAll('.clickable-row').forEach(row => {
    row.addEventListener('click', () => {
        window.location.href = row.getAttribute('data-href');
    });
});

</script>



{% endblock %}