copen/urls.py
#urls - view - template

from django.urls import path, include
from .views import Copen, ApreensaoAddView, OcorrenciaView, buscar_interno, filtrar_objetos_htmx, AtendimentoView, \
    CustodiaAddView, CustodiaEditView, MpAddView, ApreensaoRelatorioView, relatorio_resumido_apreensao

app_name = 'copen'

urlpatterns = [
    path('', Copen.as_view(), name='copen'),
    path('atendimento-add/', AtendimentoView.as_view(), name='atendimento-add'),
    path('apreensao-add/', ApreensaoAddView.as_view(), name='apreensao-add'),
    path('ocorrencia-add/', OcorrenciaView.as_view(), name='ocorrencia-add'),
    path('custodia-add/', CustodiaAddView.as_view(), name='custodia-add'),
    path('mp-add/', MpAddView.as_view(), name='mp-add'),
    path('custodia-edit/<int:pk>', CustodiaEditView.as_view(), name='custodia-edit'),
    #relatorios
    path('apreensao-relatorio/', ApreensaoRelatorioView.as_view(), name='apreensao-relatorio'),


    #pdf_relatorios
    path('relatorio-resumido-apreensao/', relatorio_resumido_apreensao, name='relatorio-resumido-apreensao'),

    #partials htmx
    path('buscar-interno/', buscar_interno, name='buscar-interno'),
    path('filtrar-objetos/', filtrar_objetos_htmx, name='filtrar-objetos'),


]

interno/urls.py
from django.urls import path
from .views import (RelatorioInterno, Internos, upload_planilha_excel, cadastrar_rosto,
                    reconhecer_interno, detalhes_interno, PopulacaoEdit,
                    get_populacao_por_unidade)
from .htmx_views import interno_list

app_name = 'interno'

urlpatterns = [
    path('', Internos.as_view(), name='interno'),
    path('upload-interno/', upload_planilha_excel, name='upload_interno'),
    path('relatorio_interno/', RelatorioInterno.as_view(), name='relatorio_interno'),
    path('populacao-edit/', PopulacaoEdit.as_view(), name='populacao_edit'),
    path('<int:interno_id>/cadastrar-rosto/', cadastrar_rosto, name='cadastrar_rosto'),
    path('reconhecer-interno/', reconhecer_interno, name='reconhecer_interno'),
    path('<int:interno_id>/detalhes/', detalhes_interno, name='detalhes_interno'),
    path('ajax/get-populacao/', get_populacao_por_unidade, name='get_populacao_por_unidade'),


    # Nova URL
]

htmx_urlpatterns = [
    path('interno_list/', interno_list, name='interno_list'),
]

urlpatterns += htmx_urlpatterns

siteservidores/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


# Apontando para a view custom_403 do app seappb
handler403 = 'seappb.views.custom_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('seappb.urls', namespace='seappb')),
    path('gesipe/', include('gesipe.urls', namespace='gesipe')),
    path('ajuda_custo/', include('ajuda_custo.urls', namespace='ajuda_custo')),
    path('servidor/', include('servidor.urls', namespace='servidor')),
    path('copen/', include('copen.urls', namespace='copen')),
    path('interno/', include('interno.urls', namespace='interno')),
    path('gestao_prisional/', include('gestao_prisional.urls', namespace='gestao_prisional')),
    path('armaria/', include('armaria.urls', namespace='armaria')),
    path('chained/', include('smart_selects.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

copen/models.py
from django.db import models
from django.utils import timezone
from seappb.models import Usuario, Unidade
from interno.models import Interno
from servidor.models import Servidor

# Create your models here.

#models atendimentos


class StatusPreso(models.Model):
    nome = models.CharField(max_length=100)
    ordem = models.IntegerField(default=0)  # Adiciona o campo 'ordem'

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ['ordem']  # Ordena os itens pelo campo 'ordem'



class Atendimento(models.Model):
    data = models.DateField(default=timezone.now)
    nome = models.CharField(max_length=255)
    prontuario = models.CharField(max_length=255, null=True, blank=True)
    localizado = models.BooleanField(default=False)
    servidor = models.ForeignKey(Servidor, on_delete=models.CASCADE, null=True, blank=True)
    outros = models.CharField(max_length=100, null=True, blank=True)
    matricula = models.CharField(max_length=20, null=True, blank=True)
    instituicao = models.CharField(max_length=100, null=True, blank=True)
    unidade = models.ForeignKey(Unidade, on_delete=models.CASCADE, null=True, blank=True)
    status_preso = models.ForeignKey(StatusPreso, on_delete=models.CASCADE, null=True, blank=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    observacao = models.TextField(null=True, blank=True)
    data_edicao = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return f"{self.data} - {self.data.strftime('%d/%m/%Y')}"


# models apreensoes
class Natureza(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ['nome']  # Ordena por nome em ordem alfabética


class Objeto(models.Model):
    nome = models.CharField(max_length=100)
    natureza = models.ForeignKey(Natureza, on_delete=models.CASCADE, related_name='objetos')

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ['nome']  # Ordena por nome em ordem alfabética


class Apreensao(models.Model):
    data = models.DateField(default=timezone.now)
    natureza = models.ForeignKey(Natureza, on_delete=models.CASCADE)
    objeto = models.ForeignKey(Objeto, on_delete=models.CASCADE)
    quantidade = models.IntegerField(default=0)  # Alterado para IntegerField
    unidade = models.ForeignKey(Unidade, on_delete=models.CASCADE)
    descricao = models.TextField()
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    observacao = models.TextField(null=True, blank=True)
    data_edicao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.natureza} - {self.data.strftime('%d/%m/%Y')}"


#tabelas custodias


class Custodia(models.Model):
    interno = models.ForeignKey(Interno, on_delete=models.CASCADE)
    unidade_hospitalar = models.CharField(max_length=100)
    unidade_solicitante = models.ForeignKey(Unidade, on_delete=models.CASCADE)
    responsavel = models.CharField(max_length=100)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    observacao = models.TextField(null=True, blank=True)
    data_entrada = models.DateField(default=timezone.now)
    data_saida = models.DateField(default=timezone.now, null=True, blank=True)
    data_edicao = models.DateTimeField(default=timezone.now)


    def __str__(self):
        data_saida_str = self.data_saida.strftime('%d/%m/%Y') if self.data_saida else 'Ainda vigente'
        return f"{self.interno} - {self.data_entrada.strftime('%d/%m/%Y')} - {data_saida_str}"



# mandados de prisao

class TipoMp(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome


class Mp(models.Model):
    tipo = models.ForeignKey(TipoMp, on_delete=models.CASCADE)
    interno = models.ForeignKey(Interno, on_delete=models.CASCADE)
    nome_mae = models.CharField(max_length=100)
    unidade = models.ForeignKey(Unidade, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    observacao = models.TextField(null=True, blank=True)
    data_cumprimento = models.DateField(default=timezone.now)
    data_edicao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.interno} - {self.data_cumprimento.strftime('%d/%m/%Y')}"





# ocorrencia model

class TipoOcorrencia(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome





class Ocorrencia(models.Model):
    data = models.DateField(default=timezone.now)
    descricao = models.TextField()
    tipo = models.ForeignKey(TipoOcorrencia, on_delete=models.CASCADE)
    unidade = models.ForeignKey(Unidade, on_delete=models.CASCADE, null=True, blank=True)
    interno = models.ForeignKey(Interno, on_delete=models.CASCADE, null=True, blank=True)
    servidor = models.ForeignKey(Servidor, on_delete=models.CASCADE, null=True, blank=True)
    outros = models.CharField(max_length=100, null=True, blank=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    observacao = models.TextField(null=True, blank=True)
    data_edicao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.descricao} - {self.data.strftime('%d/%m/%Y')}"

copen/templates/copen_apreensao_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block titulo %}
Copen - Apreensao
{% endblock %}



{% block content %}
    <div class="flex flex-col pt-4">
        <div class="flex flex-col ítems-end">
            <h1 class="text-center text-3xl pb-5 font-mono">Cadastro de Apreensão</h1>
        </div>



        <form class="mx-4 shadow rounded shadow-md border border-2 border-secondary" method="post" action="{% url 'copen:apreensao-add' %}">
            {% csrf_token %}

            <div class="flex justify-center space-x-4 w-full pb-8 pt-4">
                <!-- Campo Data -->
                <div class="w-auto">
                    <label for="id_data" class="form-label">Data:</label>
                    <input type="date" name="data" id="id_data" class="form-control" required>
                    {% if form.data.errors %}
                            <ul class="text-danger">
                                {% for error in form.data.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                </div>
                <!-- Campo unidade -->
                <div class="w-auto">
                    <label class="form-label">Unidade:</label>
                    {{form.unidade}}
                    {% if form.unidade.errors %}
                            <ul class="text-danger">
                                {% for error in form.unidade.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}

                </div>
                <!-- Campo Natureza -->
                <div class="w-auto">
                    <label class="form-label">Natureza da Apreensão:</label>
                    {{form.natureza}}
                    {% if form.natureza.errors %}
                        <ul class="text-danger">
                            {% for error in form.natureza.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                </div>
            </div>
            <div class="flex justify-center space-x-4 w-full pb-8">



                <!-- Campo Objeto -->
                <div class="w-auto">
                    <label for="id_objeto" class="form-label">Objeto:</label>
                    <select name="objeto" id="id_objeto" class="form-control">
                        <option value="">Selecione a Natureza Primeiro</option>
                        {% if form.objeto.errors %}
                        <ul class="text-danger">
                            {% for error in form.objeto.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    </select>
                </div>


                <!-- Outros Campos -->
                <div class="w-auto">
                    <label class="form-label">Quantidade:</label>
                    {{form.quantidade}}
                    <ul class="text-danger">
                        {% for error in form.objeto.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="flex justify-center space-x-4 w-full pb-8 mx-6">

                <div class="w-2/4">
                    <label for="id_descricao" class="form-label">Descrição:</label>
                    <textarea name="descricao" id="id_descricao" class="form-control" rows="3" required></textarea>
                </div>

                <div class="w-1/4">
                    <label for="id_observacao" class="form-label">Observação:</label>
                    <textarea name="observacao" id="id_observacao" class="form-control" rows="3"></textarea>
                </div>

            </div>

            <div class="flex justify-center space-x-4 w-full pb-8">
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>





<script>
    document.addEventListener('DOMContentLoaded', function() {
        const today = new Date().toISOString().split('T')[0]; // Obtém a data atual no formato YYYY-MM-DD
        const dateField = document.getElementById('id_data');
        if (dateField && !dateField.value) { // Preenche apenas se o campo estiver vazio
            dateField.value = today;
        }
    });
</script>
{% endblock %}

copen/templates/copen_atendimento_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block titulo %}
Copen -Atendimento
{% endblock %}



{% block content %}
    <div class="flex flex-col pt-4">

        <div class="flex flex-col ítems-end">
            <h1 class="text-center text-3xl pb-5 font-mono">Cadastro de Atendimento:</h1>
        </div>


        <form class="mx-4 shadow rounded shadow-md border border-2 border-secondary" method="post" action="{% url 'copen:atendimento-add' %}">
            {% csrf_token %}


            <div class="flex justify-center space-x-4 w-full pb-8 pt-4">
                <!-- Campo Data -->
                <div class="w-auto text-center">
                    <label for="id_data" class="form-label">Data:</label>
                    <input type="date" name="data" id="id_data" class="form-control" required>
                </div>
                <!-- Campo nome pesquisado -->
                <div class="w-auto text-center">
                    <label for="id_data" class="form-label">Nome Pesquisado:</label>
                    <input type="text" name="nome" id="id_nome" class="form-control" required>
                </div>
            </div>
            <div class="flex justify-center space-x-4 w-full pt-4 mx-4 pb-2">
                <h3 class="text-2xl font-semibold">Localizar Interno</h3>
            </div>
            <!-- Campo botao pesquisar inter -->
                <!-- Botão Localizar Interno -->
                <div class="w-auto text-center pb-6">
                    <button type="button" class="btn btn-primary" id="btn-localizar">Localizar</button>
                </div>
            <div class="flex flex justify-center space-x-4 items-center flex-row text-center mx-4 pb-8">
                <label class="form-label">Status</label>
                <div class="form-check">
                    {% for radio in form.localizado %}
                        <div class="flex items-center space-x-2">
                            {{ radio.tag }}
                            <label class="text-gray-900">{{ radio.choice_label }}</label>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="flex flex justify-center space-x-4 items-center flex-row text-center mx-4 pb-8">
                <!-- Campo unidade -->
                <div class="">
                    <label  class="form-label">Se Localizado, Qual Unidade ou Regime:</label>
                    {{form.unidade}}
                </div>
                <!-- Campo STATUS -->
                <div class="">
                    <label  class="form-label">Se Localizado, Qual Status:</label>
                    {{form.status_preso}}
                </div>
            </div>




            <div class="flex flex justify-center items-center flex-col w-full pb-2 pt-4 mx-4">
                <div class="flex flex-col ítems-end">
                    <h3 class="text-center text-2xl pb-2 font-semibold">Policial Penal</h3>
                </div>

                <!-- Campo servidor -->
                <div class="w-1/4 text-center mx-4 pb-8">
                    <div class="w-auto">

                        {{form.servidor}}
                    </div>
                </div>
            </div>
            <div class="flex flex justify-center items-center flex-col w-full pb-2 pt-4">
                <div class="flex flex-col ítems-end">
                    <h3 class="text-center text-2xl pb-2 font-semibold">Outras Intituições:</h3>
                </div>

                <div class="flex flex justify-center items-center flex-row text-center pb-8">
                    <!-- Campo outros -->
                    <div class="p-2">
                        <label  class="form-label">Nome / Cargo ou Função:</label>
                        {{form.outros}}
                    </div>
                    <!-- Campo matricula outros -->
                    <div class="p-2">
                        <label  class="form-label">Matrícula:</label>
                        {{form.matricula}}
                    </div>
                    <!-- Campo instituicao externa -->
                    <div class="p-2">
                        <label  class="form-label">Instituição:</label>
                        {{form.instituicao}}
                    </div>
                </div>
            </div>

            <div class="flex flex justify-center items-center flex-col w-full pb-4 pt-4">

                <!-- Campo observacao -->
                <div class="w-auto text-center">
                    <label  class="form-label">Observações:</label>
                    {{form.observacao}}
                </div>
            </div>



            <div class="flex flex justify-center items-center flex-col w-full pb-2 pt-4">
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>

<!-- Script para modificar o link -->
<script>
    document.getElementById("btn-localizar").addEventListener("click", function(event) {
        event.preventDefault();  // Evita que o link siga sem modificação

        let nomePesquisado = document.getElementById("id_nome").value.trim(); // Obtém o valor digitado

        if (nomePesquisado !== "") {
            // Criando os parâmetros da URL manualmente
            let params = new URLSearchParams();
            params.set("query", nomePesquisado);
            params.set("action", "search");

            let url = "{% url 'interno:relatorio_interno' %}?" + params.toString();
            window.open(url, "_blank"); // Abre a URL em uma nova aba
        } else {
            alert("Digite um nome antes de pesquisar.");
        }
    });
</script>






<script>
    document.addEventListener('DOMContentLoaded', function() {
        const today = new Date().toISOString().split('T')[0]; // Obtém a data atual no formato YYYY-MM-DD
        const dateField = document.getElementById('id_data');
        if (dateField && !dateField.value) { // Preenche apenas se o campo estiver vazio
            dateField.value = today;
        }
    });
</script>
{% endblock %}

copen/templates/copen_custodia_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block titulo %}
Copen - Apreensao
{% endblock %}



{% block content %}
     <div class="flex flex-col pt-4">

        <div class="flex flex-col ítems-end">
            <h1 class="text-center text-3xl pb-5 font-mono">Incluir Custódia:</h1>
        </div>
        <form class="mx-4 shadow rounded shadow-md border border-2 border-secondary" method="post" action="{% url 'copen:custodia-add' %}">
            {% csrf_token %}


            <div class="flex justify-center space-x-4 w-full pb-8 pt-4">
                <div class="w-auto">
                    <label class="form-label">Unidade Hospitalar:</label>
                    {{ form.unidade_hospitalar }}
                </div>
                <div class="w-auto">
                    <label class="form-label">Unidade Solicitante:</label>
                    {{ form.unidade_solicitante }}
                </div>
                <div class="w-auto">
                    <label class="form-label">Responsável pela Custódia:</label>
                    {{ form.responsavel }}
                </div>
            </div>
            <div class="flex justify-center space-x-4 w-full pb-8 pt-4 mx-4">
                <!-- Buscar Interno -->
                <div class="w-1/6">
                   <label class="form-label">Buscar Interno:</label>
                   {{form.interno_nome}}</div>

                <!-- Contêiner para os resultados -->
                <div id="autocomplete-results" class="mt-3"></div>

                <!-- Indicador de carregamento -->
                <div id="autocomplete-loading" style="display: none;">Carregando...</div>

                <!-- Campo não editável para exibir o interno selecionado -->
                <div class="w-2/6">
                    <label for="id_interno" class="form-label">Interno Selecionado:</label>
                    <input type="text" name="interno" id="id_interno" class="form-control" readonly placeholder="Selecione o interno na tabela abaixo">
                </div>
                <!-- Campo oculto para enviar o ID do interno -->
                <input type="hidden" name="interno_id" id="interno-id">

            </div>

            <div class="flex justify-center space-x-4 w-full pb-8 pt-4 mx-4">
                <div class="form-group">
                    {{ form.data_entrada.label_tag }}
                    {{ form.data_entrada }}
                </div>
                <div class="form-group">
                    {{ form.data_saida.label_tag }}
                    {{ form.data_saida }}
                </div>
            </div>



            <div class="flex justify-center space-x-4 w-full pb-8 pt-4 mx-4">
                <div class="form-group">
                    {{ form.observacao.label_tag }}
                    {{ form.observacao }}
                </div>
            </div>

            <div class="flex justify-center space-x-4 w-full pb-8 pt-4 mx-4">
                <button type="submit" class="btn btn-primary mt-3">Salvar</button>
            </div>
        </form>
    </div>

<script>
        function setInterno(id, nome) {
        // Preenche o campo não editável com o nome do interno
        document.getElementById('id_interno').value = nome;

        // Preenche ou cria o campo oculto para o ID do interno
        const hiddenField = document.getElementById('interno-id');
        if (!hiddenField) {
            const input = document.createElement('input');
            input.type = 'hidden';
            input.name = 'interno_id';  // Importante: o name deve ser interno_id
            input.id = 'interno-id';
            input.value = id;
            document.querySelector('form').appendChild(input);
        } else {
            hiddenField.value = id;
        }

        // Limpa os resultados da tabela
        document.getElementById('autocomplete-results').innerHTML = '';
    }

</script>





<script>
    document.addEventListener('DOMContentLoaded', function() {
        const today = new Date().toISOString().split('T')[0]; // Obtém a data atual no formato YYYY-MM-DD
        const dateField = document.getElementById('id_data');
        if (dateField && !dateField.value) { // Preenche apenas se o campo estiver vazio
            dateField.value = today;
        }
    });
</script>
{% endblock %}

copen/templates/copen_mp_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block titulo %}
Copen - Apreensao
{% endblock %}



{% block content %}
     <div class="flex flex-col pt-4">

        <div class="flex flex-col ítems-end">
            <h1 class="text-center text-3xl pb-5 font-mono">Cumprimento de Mandado de Prisão:</h1>
        </div>
        <form class="mx-4 shadow rounded shadow-md border border-2 border-secondary" method="post" action="{% url 'copen:mp-add' %}">
            {% csrf_token %}


            <div class="flex justify-center space-x-4 w-full pb-8 pt-4">
                <div class="w-auto">
                    <label class="form-label">Data de Cumprimento:</label>
                    {{ form.data_cumprimento }}
                </div>
                <div class="w-auto">
                    <label class="form-label">Unidade:</label>
                    {{ form.unidade }}
                </div>
                <div class="w-auto">
                    <label class="form-label">Tipo de Cumprimento:</label>
                    {{ form.tipo }}
                </div>
            </div>
            <div class="flex justify-center space-x-4 w-full pb-8 pt-4 mx-4">
                <!-- Buscar Interno -->
                <div class="w-1/6">
                   <label class="form-label">Nome do Interno:</label>
                   {{form.interno_nome}}</div>

                <!-- Contêiner para os resultados -->
                <div id="autocomplete-results" class="mt-3"></div>

                <!-- Indicador de carregamento -->
                <div id="autocomplete-loading" style="display: none;">Carregando...</div>

                <!-- Campo não editável para exibir o interno selecionado -->
                <div class="w-2/6">
                    <label for="id_interno" class="form-label">Interno Selecionado:</label>
                    <input type="text" name="interno" id="id_interno" class="form-control" readonly placeholder="Selecione o interno na tabela abaixo">
                </div>
                <!-- Campo oculto para enviar o ID do interno -->
                <input type="hidden" name="interno_id" id="interno-id">

            </div>

            <div class="flex justify-center space-x-4 w-full pb-8 pt-4 mx-4">
                <div class="w-auto">
                    <label >Nome da Mãe:</label>
                    {{form.nome_mae}}
                </div>

            </div>



            <div class="flex justify-center space-x-4 w-full pb-8 pt-4 mx-4">
                <div class="form-group">
                    {{ form.observacao.label_tag }}
                    {{ form.observacao }}
                </div>
            </div>

            <div class="flex justify-center space-x-4 w-full pb-8 pt-4 mx-4">
                <button type="submit" class="btn btn-primary mt-3">Salvar</button>
            </div>
        </form>
    </div>

<script>
            function setInterno(id, nome, nomeMae) {
        // Preenche o campo não editável com o nome do interno
        document.getElementById('id_interno').value = nome;

        // Preenche o campo do nome da mãe
        document.getElementById('id_nome_mae').value = nomeMae;

        // Preenche ou cria o campo oculto para o ID do interno
        const hiddenField = document.getElementById('interno-id');
        if (!hiddenField) {
            const input = document.createElement('input');
            input.type = 'hidden';
            input.name = 'interno_id';  // Importante: o name deve ser interno_id
            input.id = 'interno-id';
            input.value = id;
            document.querySelector('form').appendChild(input);
        } else {
            hiddenField.value = id;
        }

        // Limpa os resultados da tabela
        document.getElementById('autocomplete-results').innerHTML = '';
    }

</script>





<script>
    document.addEventListener('DOMContentLoaded', function() {
        const today = new Date().toISOString().split('T')[0]; // Obtém a data atual no formato YYYY-MM-DD
        const dateField = document.getElementById('id_data_cumprimento');
        if (dateField && !dateField.value) { // Preenche apenas se o campo estiver vazio
            dateField.value = today;
        }
    });
</script>
{% endblock %}